### ISSUE TITLE
`container` debe contener al h1, img y button

### ISSUE THREAD

**Issue by nhsz** [quintanamartin/memeoftheday#3]
Esta estructura no cumple con [lo que pide la consigna](https://github.com/undefinedschool/project-3-meme-of-the-day/#parte-5-render-)

```html
<main>
  <h1>Meme of the Day</h1>
    <div class="container">
      <img src="" class="meme" alt="" />
    </div>
    <button class="get-meme">Get Meme!</button>
</main>
```

**Comment by quintanamartin** [comment]
Ya esta solucionado, no habia aplicado ninguna regla de la consigna
