### ISSUE TITLE
retornar `response.json()` directamente para simplificar el código

### ISSUE THREAD

**Issue by nhsz** [quintanamartin/memeoftheday#4]
[Acá](https://github.com/quintanamartin/memeoftheday/blob/738163f030d0e91e4097f08e55bf1f458413f16c/utils.js#L7) se puede retornar directamente `response.json()` y evitamos encadenar el `response => response.json()` posterior

**Comment by quintanamartin** [comment]
Modificada la funcion checkstatus para que devuelva el json
